######################################################################
# Automatically generated by qmake (3.0) Wed Feb 26 20:58:42 2014
######################################################################

TEMPLATE = app
TARGET = hnefatafl
QT += widgets
INCLUDEPATH += . 

# Input
SOURCES += core.cpp hnefatafl.cpp window.cpp
HEADERS += core.h window.h

QMAKE_LFLAGS += -L../hnefatafl
QMAKE_LIBS += -ljson_linux-gcc-4.8.2_libmt
QMAKE_CXXFLAGS += -std=c++0x
